name: Build production
on: 
  push:
    tags: 
      - '*-production'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - name: Cache modules
#        uses: actions/cache@v3
#        with:
#          path: ~/nodemoduulit
#          key: ${{ runner.os }}
      - name: Set API url
        run: ./setApiUrl.sh
        env:
          PROD_API_URL: ${{ secrets.PROD_API_URL }}
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: petjal2/client-opinvoimala-frontend
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            ENVIRONMENT=production